const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateInvoice = (order) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 40,
        size: 'A4',
        info: {
          Title: `Curation Registry - ${order._id}`,
          Author: 'RongRani',
        }
      });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // --- Color Palette ---
      const colors = {
        royalMaroon: '#580F1B', // Richer, darker maroon
        bespokeGold: '#C5A059', // Elegant muted gold
        midnight: '#0F172A',
        slate: '#475569',
        cream: '#FDFCFB',        // Subtlest off-white for background
        success: '#10B981'
      };

      // 1. HEADER: The Signature Look
      doc.rect(0, 0, 595, 140).fill(colors.royalMaroon);
      doc.rect(0, 140, 595, 5).fill(colors.bespokeGold); // Thicker gold accents

      // Decorative Accent
      doc.lineWidth(0.5).strokeColor(colors.bespokeGold).opacity(0.3);
      doc.moveTo(40, 115).lineTo(555, 115).stroke();
      doc.opacity(1);

      // Logo & Brand
      const logoPath = path.join(__dirname, '../../public/RongRani-Circle.png');
      if (fs.existsSync(logoPath)) {
        doc.image(logoPath, 45, 25, { width: 70 });
        doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(28).text('RongRani', 125, 38);
        doc.fontSize(10).font('Helvetica').text('THE ART OF BESPOKE GIFTING', 125, 70, { characterSpacing: 2 });
      } else {
        doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(36).text('RongRani', 45, 35);
        doc.fontSize(12).font('Helvetica').text('THE ART OF BESPOKE GIFTING', 45, 75);
      }

      // Registry Title & Challan Header
      doc.fontSize(24).font('Helvetica-Bold').text('INVOICE / CHALLAN', 330, 40, { align: 'right', width: 220 });
      doc.fontSize(10).font('Helvetica').text('OFFICIAL DELIVERY MANIFEST', 330, 70, { align: 'right', width: 220, characterSpacing: 1.5 });
      doc.fontSize(8).text(`Auto-Generated by System`, 330, 85, { align: 'right', width: 220 });

      // 2. REGISTRY DETAILS (Floating Box)
      let yPos = 165;
      doc.roundedRect(40, yPos, 515, 70, 4).fill(colors.cream);
      doc.roundedRect(40, yPos, 515, 70, 4).lineWidth(1).strokeColor(colors.bespokeGold).stroke();

      doc.fontSize(8).fillColor(colors.slate).font('Helvetica-Bold');
      doc.text('ORDER REFERENCE', 60, yPos + 15);
      doc.text('ORDER DATE', 200, yPos + 15);
      doc.text('PAYMENT METHOD', 330, yPos + 15);
      doc.text('PAYMENT STATUS', 460, yPos + 15);

      doc.fontSize(14).fillColor(colors.royalMaroon).font('Helvetica-Bold');
      doc.text(`#${order.orderId || order._id.toString().substring(0, 8).toUpperCase()}`, 60, yPos + 32);

      const orderDate = new Date(order.createdAt).toLocaleDateString('en-BD', {
        day: '2-digit', month: 'short', year: 'numeric'
      });
      doc.fontSize(11).fillColor(colors.midnight).font('Helvetica').text(orderDate, 200, yPos + 34);
      doc.text(order.paymentMethod === 'cod' ? 'CASH ON DELIVERY' : order.paymentMethod?.toUpperCase(), 330, yPos + 34);

      const pStatus = order.paymentStatus || 'pending';
      const statusColor = pStatus === 'paid' ? colors.success : '#D97706';
      doc.fillColor(statusColor).font('Helvetica-Bold').text(pStatus.toUpperCase(), 460, yPos + 34);

      // 3. DESTINATION DOSSIER (Shipping)
      yPos = 260;
      doc.fontSize(11).fillColor(colors.bespokeGold).font('Helvetica-Bold').text('CLIENT DESTINATION', 40, yPos, { characterSpacing: 1 });
      doc.rect(40, yPos + 15, 515, 1).fill(colors.slate).opacity(0.1);
      doc.opacity(1);

      yPos += 25;
      const shipping = order.shippingAddress || {};

      // Address Box
      doc.rect(40, yPos, 300, 85).fill('#F8FAFC'); // Light background for address

      doc.fontSize(16).fillColor(colors.midnight).font('Helvetica-Bold').text(shipping.name || 'Valued Guest', 50, yPos + 10);

      doc.fontSize(10).fillColor(colors.midnight).font('Helvetica').text(shipping.phone || 'N/A', 50, yPos + 32);
      if (shipping.email) doc.text(shipping.email, 160, yPos + 32);

      const fullAddress = [
        shipping.street,
        shipping.union,
        shipping.subDistrict,
        shipping.district,
        shipping.city,
        shipping.zipCode || shipping.postalCode
      ].filter(Boolean).join(', ');

      doc.fontSize(10).fillColor(colors.slate).text(fullAddress, 50, yPos + 48, { width: 280, lineGap: 2 });

      // Right side: Certified Badge
      doc.image(logoPath, 420, yPos, { width: 40, opacity: 0.5 }); // Watermark logo
      doc.fillColor(colors.bespokeGold).fontSize(8).font('Helvetica-Bold').text('CERTIFIED ARTISAN QUALITY', 380, yPos + 50, { align: 'center', width: 120 });
      doc.fillColor(colors.slate).font('Helvetica').fontSize(6).text('Inspected & Approved for Delivery', 380, yPos + 62, { align: 'center', width: 120 });

      // 4. THE CURATION TABLE
      yPos = Math.max(yPos + 110, 390);
      doc.rect(40, yPos, 515, 25).fill(colors.royalMaroon);
      doc.font('Helvetica-Bold').fontSize(9).fillColor('#FFFFFF');
      doc.text('ITEM DESCRIPTION', 60, yPos + 8);
      doc.text('QTY', 320, yPos + 8, { width: 40, align: 'center' });
      doc.text('PRICE', 370, yPos + 8, { width: 70, align: 'right' });
      doc.text('TOTAL', 450, yPos + 8, { width: 90, align: 'right' });

      yPos += 25;
      doc.fillColor(colors.midnight).font('Helvetica').fontSize(10);

      order.items.forEach((item, index) => {
        if (index % 2 === 0) {
          doc.rect(40, yPos, 515, 24).fill('#F9FAFB');
        }
        doc.fillColor(colors.midnight).text(item.name || 'Artisan Work', 60, yPos + 7, { width: 250, ellipsis: true });
        doc.text(item.quantity.toString(), 320, yPos + 7, { width: 40, align: 'center' });
        doc.text(item.price.toLocaleString(), 370, yPos + 7, { width: 70, align: 'right' });
        doc.font('Helvetica-Bold').text((item.price * item.quantity).toLocaleString(), 450, yPos + 7, { width: 90, align: 'right' });
        doc.font('Helvetica');
        yPos += 24;
      });

      // 5. FINANCIAL SUMMARY
      yPos += 15;
      const summaryX = 350;
      doc.moveTo(summaryX, yPos).lineTo(555, yPos).strokeColor(colors.slate).lineWidth(0.5).stroke();
      yPos += 10;

      doc.fontSize(9).fillColor(colors.slate).font('Helvetica');
      doc.text('Subtotal:', summaryX, yPos, { width: 100, align: 'right' });
      doc.fillColor(colors.midnight).text(`Tk ${order.subtotal.toLocaleString()}`, 450, yPos, { width: 90, align: 'right' });
      yPos += 14;

      const shippingCharge = order.shipping || order.delivery?.charge || 0;
      doc.fillColor(colors.slate).text('Delivery Charge:', summaryX, yPos, { width: 100, align: 'right' });
      doc.fillColor(colors.midnight).text(`Tk ${shippingCharge.toLocaleString()}`, 450, yPos, { width: 90, align: 'right' });
      yPos += 14;

      if (order.discount > 0) {
        doc.fillColor(colors.slate).text('Discount:', summaryX, yPos, { width: 100, align: 'right' });
        doc.fillColor('#10B981').text(`-Tk ${order.discount.toLocaleString()}`, 450, yPos, { width: 90, align: 'right' });
        yPos += 14;
      }

      // Grand Total
      doc.rect(summaryX, yPos + 5, 205, 30).fill(colors.royalMaroon);
      doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(12).text('TOTAL DUE', summaryX + 10, yPos + 15);
      doc.fontSize(16).text(`Tk ${order.total.toLocaleString()}`, 450, yPos + 13, { width: 90, align: 'right' });


      // 6. SIGNATURE SECTION (Bottom of Page)
      const sigY = 700;

      // Customer Signature
      doc.moveTo(60, sigY).lineTo(220, sigY).strokeColor(colors.midnight).lineWidth(1).stroke();
      doc.fontSize(10).fillColor(colors.midnight).font('Helvetica-Bold').text('Customer Signature', 60, sigY + 10, { width: 160, align: 'center' });
      doc.fontSize(8).fillColor(colors.slate).font('Helvetica').text('Received in good condition', 60, sigY + 22, { width: 160, align: 'center' });

      // Admin/Authority Signature
      doc.moveTo(380, sigY).lineTo(540, sigY).strokeColor(colors.midnight).lineWidth(1).stroke();
      doc.fontSize(10).fillColor(colors.royalMaroon).font('Helvetica-Bold').text('Authorized Signature', 380, sigY + 10, { width: 160, align: 'center' });
      doc.fontSize(8).fillColor(colors.slate).font('Helvetica').text('RongRani Authority', 380, sigY + 22, { width: 160, align: 'center' });

      // Footer Branding
      doc.fontSize(7).fillColor(colors.slate).text('© 2026 RongRani - Curated with Passion by Salah Uddin Kader. All Rights Reserved.', 0, 790, { align: 'center', width: 595 });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

const generateReport = (data, type) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Header
      doc.fontSize(20).text('RongRani', { align: 'center' });
      doc.fontSize(14).text(`${type} Report`, { align: 'center' });
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown();

      // Report content based on type
      if (type === 'Sales') {
        doc.fontSize(12);
        doc.text(`Total Orders: ${data.totalOrders}`);
        doc.text(`Total Revenue: $${data.totalRevenue.toFixed(2)}`);
        doc.text(`Average Order Value: $${data.averageOrderValue.toFixed(2)}`);
        doc.moveDown();

        // Monthly breakdown
        if (data.monthlyData) {
          doc.text('Monthly Sales:');
          data.monthlyData.forEach(month => {
            doc.text(`${month.month}: $${month.revenue.toFixed(2)} (${month.orders} orders)`);
          });
        }
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generateInvoice,
  generateReport,
};